
//This file is generated by SceneWindow.cs
using UnityEngine;
using System.Collections;

public static class SceneIndex
{
    //This string will be registered by pushing [Apply To Build Settings] button
    
}
