//This file is generated by SceneWindow.cs
using UnityEngine;
using System.Collections;

public static class SceneIndex
{
    //This string will be registered by pushing [Apply To Build Settings] button
    

    //enum ENUM_SCENE
    public enum ENUM_SCENE
    { 
    };

    public static string[] Path_Index = 
    { 
    };
}
